version: "3"
services:
      sportstore:
          build:
          ports:
          -"5000:5000"
      environment:
          -ASPNETCORE_ENVRONMENT = PRODUCTION
      depends_on: 
          -sqlserver
sqlserver:
      image:"mcr.microsoft.com/mssql/server"
      environment:"mogosa.2008"
      ACCEPT_EULA: "Y"